### ISSUE TITLE
Add sign up/ sign in pages

### ISSUE THREAD

**Issue by wandergithub** [wandergithub/e-commerce#17]
Add pages so users can register and sign in to the page.

Actually, I just expect the plain page and forms. Then we can work on API interactions and form submissions.

**Comment by Lz-01** [comment]
can i have this issue ?

**Comment by wandergithub** [comment]
# Sure, @Lz-01 
I'll assign you.

**Comment by Lz-01** [comment]
@wandergithub can you explain me the Route of this page? And when should the login Page appear?

**Comment by wandergithub** [comment]
@Lz-01 Right now it would be ok just to create two routes, one for each page.

The logging page should appear when the users click the profile icon:
![image](https://user-images.githubusercontent.com/55507343/220426287-6dd1171e-7e50-45bc-9a17-de3a5b4ad29a.png)

For now, it would be ok just to add the pages and forms. With the respective Material-UI style. I mean you don't have to worry about submission.

**Comment by Lz-01** [comment]
I created the forms including their routes. What do you mean by the respective Material UI style? Are these CSS files you created or are you using an external library?

**Comment by wandergithub** [comment]
@Lz-01 You can add [Material-ui](https://mui.com/material-ui/react-text-field/) Styled components if you prefer as I'm doing with all the web components. 

This way the page has a homogeneous look.
I would recommend using it. One of my main goals with this project is to expose us to as many different technologies as possible and to expand our skill set.

Here is a screenshot of the input field component that they provide: 

![image](https://user-images.githubusercontent.com/55507343/220604894-5e6c46e1-5f9c-4054-9891-b251df29980c.png)

**Comment by Lz-01** [comment]
@wandergithub finished with #17. I would like to make a pull request/ push my commit.

**Comment by wandergithub** [comment]
@Lz-01 Please make a PR so I can review the changes.
